global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'data-platform'
    static_configs:
      - targets: ['data-platform:8080']
    scrape_interval: 5s
    metrics_path: '/metrics'
